### PR TITLE
Add new function

### PR DESCRIPTION
**Pull request by ghost**
1.load more  review's count control
2.automatically close firefox browser

### CODE REVIEW

**Comment by rhaarm** [comment]
1. Why is the script designed to stop at 40 iterations? Maybe add this to the class init for maxitems displayed?
2. Why is this necessary, when the **del** should take care of this, but just realized that the super() is declared incorrectly, I'll have to fix that. Also, will closing the driver early cause issues with parsing the response from self.driver.page_source or is the last known page_source stored in memory after closing?

**Comment by ghost** [comment]
Thank you for your response.

First, I really thank you for your this project!!

it helps my research a lot!!

thank you!

About problem:

1.
you are right.

Sorry,I just want to limit the the number of reviews if I just want to scrape some parts of the reviews.

2.
In my opinion, if I want to scrape many games of the commands at the same time and that will produce many firefox browser when completed.
It will produce too much memory.

## I use the windows .bat to do many commands, following:

start.bat --> scrapy runspider D:\Python\review_scraper\review_scraper\spiders\steamreviews.py -a appid=282350 -o NBA2K15.json

start2.bat --> scrapy runspider D:\Python\review_scraper\review_scraper\spiders\steamreviews.py -a appid=370240 -o NBA2K16.json

do_all.bat -- > call start.bat call start2.bat

---

## other problem:

I found a problem about output to .json file,

If the game's reviews has too much, For example game: GTA V 

when the scrapyspider get all reviews and next it will be shut down to export empty .json file

**Comment by rhaarm** [comment]
I believe the issue with the json file being empty is because the browser was being closed premature. When I get time to make changes I'll look at your other issues.

**Comment by ghost** [comment]
;)

**Comment by rhaarm** [comment]
Well, I have some good news, I'm recreating this scraper to not use selenium or scrapy. Also, it will support Python 3 and async. I found that I can parse the requested data from the LoadMoreReviewsall javascript action. It should make it faster and not require a GUI (so run on a Linux shell).

**Comment by ghost** [comment]
Nice job! :+1:

**Comment by rhaarm** [comment]
I have updated to a new version, no async just yet, but it doesn't require scrapy anymore.

**Comment by ghost** [comment]
I have saw it.
Thank you so much!!
you really help me a lot!!

:dancer:

**Pull request closed without merging**
